name: mrc
version: 0.1.0.0
github: "speculative/mrc"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/mrc#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - heap

library:
  source-dirs: src

executables:
  mrc-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mrc

tests:
  mrc-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mrc
